# Generated by Django 4.0.3 on 2022-04-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('copy', 'Копирование трейдера'), ('top_up_balance', 'Пополнение баланса'), ('withdraw', 'Вывод'), ('join_group', 'Присоединение к группе')], max_length=30, verbose_name='Тип действия')),
                ('amount', models.PositiveSmallIntegerField(null=True, verbose_name='Сумма средств')),
                ('group', models.CharField(blank=True, max_length=150, verbose_name='Слаг группы')),
                ('trader', models.CharField(blank=True, max_length=150, verbose_name='Трейдер')),
                ('top_up_method', models.CharField(blank=True, max_length=50, verbose_name='Способ пополнения баланса')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('not_success', 'Не успешно'), ('waiting', 'Ожидание')], max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
            },
        ),
    ]
