# Generated by Django 4.0.3 on 2022-04-14 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('invested_sum', models.PositiveSmallIntegerField(verbose_name='Инвестированная сумма')),
            ],
        ),
        migrations.CreateModel(
            name='TradeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(default=uuid.UUID('5217fef8-55f4-45bb-859f-236d1867cb62'), max_length=150, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('group_size', models.PositiveSmallIntegerField(default=5, verbose_name='Максимальное количество инвесторов')),
                ('need_sum', models.PositiveSmallIntegerField(verbose_name='Необходимая сумма')),
                ('min_entry_sum', models.PositiveSmallIntegerField(verbose_name='Минимальная сумма входа')),
                ('max_entry_sum', models.PositiveSmallIntegerField(verbose_name='Максимальная сумма входа')),
            ],
            options={
                'verbose_name': 'Группа трейдера',
                'verbose_name_plural': 'Группы трейдеров',
            },
        ),
    ]
