# Generated by Django 4.0.3 on 2022-04-11 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('copytrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradegroup',
            name='slug',
            field=models.SlugField(default=uuid.UUID('86f8e29e-41f8-4504-920f-0c091b3f6b68'), max_length=150, unique=True),
        ),
    ]
