# Generated by Django 4.0.3 on 2022-04-14 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('copytrade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradegroup',
            name='investors',
            field=models.ManyToManyField(through='copytrade.Membership', to=settings.AUTH_USER_MODEL, verbose_name='Инвесторы'),
        ),
        migrations.AddField(
            model_name='tradegroup',
            name='trader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='users.trader', verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='copytrade.tradegroup'),
        ),
        migrations.AddField(
            model_name='membership',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
