# Generated by Django 4.0.3 on 2022-05-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradegroup',
            name='group_type',
            field=models.CharField(choices=[('trade', 'трейдинг'), ('other', 'другое'), ('ico', 'ico')], default='trade', max_length=10, verbose_name='Тип группы'),
            preserve_default=False,
        ),
    ]
