# Generated by Django 4.0.3 on 2022-04-15 03:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('copytrade', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradegroup',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5a1ef208-88ab-4047-bd89-eb14c7780116'), max_length=150, unique=True),
        ),
    ]
