# Generated by Django 4.0.3 on 2022-04-15 04:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('copytrade', '0003_alter_tradegroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradegroup',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f7e02928-5b36-4ec4-959e-911184ee9e5d'), max_length=150, unique=True),
        ),
    ]
