# Generated by Django 4.0.3 on 2022-04-15 05:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('copytrade', '0004_alter_tradegroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradegroup',
            name='slug',
            field=models.SlugField(default=uuid.UUID('40315ff7-a061-4b97-8b76-9edc6cce8097'), max_length=150, unique=True),
        ),
    ]
