# Generated by Django 4.0.3 on 2022-05-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copytrade', '0005_alter_tradegroup_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Членство в группе', 'verbose_name_plural': 'Членства в группах'},
        ),
    ]
