# Generated by Django 4.0.3 on 2022-04-15 06:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('copytrade', '0005_alter_tradegroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradegroup',
            name='slug',
            field=models.SlugField(default=uuid.UUID('82657cf1-79c4-449c-a80a-fc0be081b98f'), max_length=150, unique=True),
        ),
    ]
