# Generated by Django 4.0.3 on 2022-06-02 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrade', '0006_alter_membership_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradegroup',
            name='percent_from_income',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент от прибыли'),
            preserve_default=False,
        ),
    ]
