# Generated by Django 4.0.3 on 2022-06-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrade', '0007_tradegroup_percent_from_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradegroup',
            name='trader_binance_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Баланс трейдера в binance на момент вывода средств'),
        ),
    ]
