# Generated by Django 4.0.3 on 2022-06-03 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copytrade', '0008_tradegroup_trader_binance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='copytrade.tradegroup'),
        ),
    ]
