# Generated by Django 4.0.3 on 2022-06-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrade', '0009_alter_membership_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
