# Generated by Django 4.0.3 on 2022-06-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_withdraw_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='paymentordertether',
            name='paid',
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('success', 'успешно'), ('expectation', 'ожидание'), ('not_success', 'не успешно')], default='expectation', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='paymentordertether',
            name='status',
            field=models.CharField(choices=[('success', 'успешно'), ('expectation', 'ожидание'), ('not_success', 'не успешно')], default='expectation', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('success', 'успешно'), ('expectation', 'ожидание'), ('not_success', 'не успешно')], default='expectation', max_length=20, verbose_name='Статус'),
        ),
    ]
