# Generated by Django 4.0.3 on 2022-06-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_paymentorder_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс по отношению к рублю'),
        ),
    ]
