# Generated by Django 4.0.3 on 2022-06-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_currency_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentordertether',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Сумма'),
        ),
    ]
