# Generated by Django 4.0.3 on 2022-04-15 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='inn',
            field=models.CharField(max_length=14, unique=True, verbose_name='Инн'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trader', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
