# Generated by Django 4.0.3 on 2022-04-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_documentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Номер телефона'),
        ),
    ]
