# Generated by Django 4.0.3 on 2022-04-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_document_inn_alter_trader_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('accepted', 'принято'), ('refused', 'отклонено'), ('on_consideration', 'на рассмотрении')], default='on_consideration', max_length=25),
        ),
    ]
