# Generated by Django 4.0.3 on 2022-04-11 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='inn',
        ),
        migrations.AddField(
            model_name='document',
            name='address',
            field=models.CharField(default='1', max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='birth_day',
            field=models.DateField(default='2022-4-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='city',
            field=models.CharField(default='1', max_length=100, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='country',
            field=models.CharField(default='1', max_length=100, verbose_name='Страна проживания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='first_name',
            field=models.CharField(default='1', max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='inn',
            field=models.CharField(default='1', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Неверный инн', regex='^(1|2){1}\\d{13}$')], verbose_name='Инн'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='last_name',
            field=models.CharField(default='1', max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='passport_number',
            field=models.CharField(default='1', max_length=100, unique=True, verbose_name='Номер паспорта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('accepted', 'принято'), ('refused', 'отклонено'), ('on_consideration', 'на рассмотрении')], default=3),
        ),
    ]
