# Generated by Django 4.0.3 on 2022-04-28 06:20

import apps.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_city_alter_document_birth_day'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
    ]
